id: 80bd7eaf-89c3-4b95-8fd8-c34ee153a70e
name: ProjectContext
type: c4-project
caepVersion: 6
description: This is a sample project configuration for C4 model generation.
children:
- id: 31989209-973d-4fff-b75d-ec9b175887e7
  type: software-system
- id: 3197973b-5db5-4655-a99c-6342e2c20a1a
  type: person
tenantId: 5f37364f-201e-47ea-2e89-08dd02619fda
